### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by theaidem** [tidwall/buntdb#12]
Hi, when try to ran this code:
```go
package main

import (
	"fmt"
	"log"
	"math/rand"
	"time"

	"github.com/tidwall/buntdb"
)

var count = 1000

func init() {
	rand.Seed(time.Now().UnixNano())
}

func main() {
	db, err := buntdb.Open("data.db")
	if err != nil {
		log.Fatal(err)
	}
	defer db.Close()

	db.CreateIndex("ages", "user:*:age", buntdb.IndexInt)

	for i := 0; i < 10; i++ {

		fmt.Println("iteration: ", i)

		db.Update(func(tx *buntdb.Tx) error {
			for j := 0; j < count; j++ {
				key := fmt.Sprintf("user:%d:age", j)
				val := fmt.Sprintf("%d", rand.Intn(100))
				tx.Set(key, val, nil)
			}
			return nil
		})

		db.Update(func(tx *buntdb.Tx) error {
			tx.Ascend("ages", func(key, val string) bool {
				_, err := tx.Delete(key)
				if err != nil {
					log.Fatal(err)
				}
				return true
			})
			return nil
		})

	}

}
```

I've got a panic on different iteration

```bash
panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x50c8a0, 0xc42000a1a0)
        /home/theaidem/.envirius/envs/develope/go/src/runtime/panic.go:500 +0x1a1
github.com/tidwall/btree.(*node).iterate(0xc4200127c0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x520100, 0xc420043d40, 0x4fa280, 0xc4200161e0, ...)
        /home/theaidem/work/golang/sandbox/buntdb_ex/src/github.com/tidwall/btree/btree.go:459 +0x743
github.com/tidwall/btree.(*BTree).Ascend(0xc420014e70, 0xc420043d40)
        /home/theaidem/work/golang/sandbox/buntdb_ex/src/github.com/tidwall/btree/btree.go:637 +0x88
github.com/tidwall/buntdb.(*Tx).scan(0xc420010540, 0xc420000000, 0x52d7f4, 0x4, 0x0, 0x0, 0x0, 0x0, 0xc420043df8, 0xc420043e08, ...)
        /home/theaidem/work/golang/sandbox/buntdb_ex/src/github.com/tidwall/buntdb/buntdb.go:1347 +0x317
github.com/tidwall/buntdb.(*Tx).Ascend(0xc420010540, 0x52d7f4, 0x4, 0xc420043df8, 0xc420043e20, 0x46f040)
        /home/theaidem/work/golang/sandbox/buntdb_ex/src/github.com/tidwall/buntdb/buntdb.go:1434 +0x80
main.main.func2(0xc420010540, 0x53c298, 0xc420010540)
        /home/theaidem/work/golang/sandbox/buntdb_ex/main.go:47 +0x5b
github.com/tidwall/buntdb.(*DB).managed(0xc42008a000, 0x1, 0x53c2b0, 0x0, 0x0)
        /home/theaidem/work/golang/sandbox/buntdb_ex/src/github.com/tidwall/buntdb/buntdb.go:869 +0xf7
github.com/tidwall/buntdb.(*DB).Update(0xc42008a000, 0x53c2b0, 0x0, 0x0)
        /home/theaidem/work/golang/sandbox/buntdb_ex/src/github.com/tidwall/buntdb/buntdb.go:892 +0x3a
main.main()
        /home/theaidem/work/golang/sandbox/buntdb_ex/main.go:49 +0x244
exit status 2
```

my go version is 1.7
not sure, probably the issue relate tidwall/btree package
any ideas?

**Comment by tidwall** [comment]
This issue is that it's not possible to call `tx.Delete` inside an iterator  such as`tx.Ascend`. 
Btrees do not allow mutation during iteration. 

An alternative is to:

```go
db.Update(func(tx *buntdb.Tx) error {
    var delkeys []string
    tx.Ascend("ages", func(key, val string) bool {
        delkeys = append(delkeys, key)
        return true
    })
    for _, key := range delkeys{
        _, err := tx.Delete(key)
        if err != nil{
            return err
        }
    }            
    return nil
})
````

There should be guard against this in the BuntDB code.

**Comment by tidwall** [comment]
And thanks for reporting this! 👍

**Comment by tidwall** [comment]
I just pushed an update that will return an error when calling Set or Delete while iterating. This fixes the panic issue.
