### ISSUE TITLE
Shrink, panic to many open files

### ISSUE THREAD

**Issue by gebv** [tidwall/buntdb#23]
~40 recording per seconds
small data (max 1Kb), raw json, without indexes
25/70 write and read

init code
```golang
db, err := buntdb.Open("_workspace/_cache.db")
	if err != nil {
		return
	}
	db.SetConfig(buntdb.Config{
		SyncPolicy:         buntdb.EverySecond,
	})
```

log error
```
panic: open _workspace/_cache.db: too many open files

goroutine 39 [running]:
github.com/tidwall/buntdb.(*DB).Shrink.func4(0xc4200e26e0, 0xc420172480, 0x14, 0xab24, 0xc43805e2d8, 0xc439733920, 0x18, 0x0, 0x0)
	/go/src/github.com/tidwall/buntdb/buntdb.go:738 +0x326
github.com/tidwall/buntdb.(*DB).Shrink(0xc4200e26e0, 0x0, 0x0)
	/go/src/github.com/tidwall/buntdb/buntdb.go:746 +0x2db
github.com/tidwall/buntdb.(*DB).backgroundManager(0xc4200e26e0)
	/go/src/github.com/tidwall/buntdb/buntdb.go:602 +0x247
created by github.com/tidwall/buntdb.Open
	/go/src/github.com/tidwall/buntdb/buntdb.go:165 +0x206

real	1m46.244s
user	0m34.317s
sys	0m2.755s
```

**Comment by billyplus** [comment]
could you show more code to see what happened?
seen like you call buntdb.Open() too many time.

**Comment by gebv** [comment]
My error, closed
