### ISSUE TITLE
Tests fail with Go 1.14 race detector. 

### ISSUE THREAD

**Issue by owais** [tidwall/buntdb#62]
Context: https://golang.org/doc/go1.14#compiler

Test output:
```
go test -v -race ./...
=== RUN   TestBackgroudOperations
--- PASS: TestBackgroudOperations (3.46s)
=== RUN   TestSaveLoad
--- PASS: TestSaveLoad (0.00s)
=== RUN   TestMutatingIterator
--- PASS: TestMutatingIterator (0.19s)
=== RUN   TestCaseInsensitiveIndex
--- PASS: TestCaseInsensitiveIndex (0.03s)
=== RUN   TestIndexTransaction
--- PASS: TestIndexTransaction (0.01s)
=== RUN   TestDeleteAll
--- PASS: TestDeleteAll (0.02s)
=== RUN   TestAscendEqual
--- PASS: TestAscendEqual (0.02s)
=== RUN   TestDescendEqual
--- PASS: TestDescendEqual (0.02s)
=== RUN   TestVariousTx
fatal error: checkptr: unsafe pointer conversion

goroutine 27 [running]:
runtime.throw(0x12c2d5f, 0x23)
	/usr/local/go/src/runtime/panic.go:1116 +0x72 fp=0xc0001372e8 sp=0xc0001372b8 pc=0x1070f52
runtime.checkptrAlignment(0xc0001692c0, 0x12a37a0, 0x1)
	/usr/local/go/src/runtime/checkptr.go:20 +0xc9 fp=0xc000137318 sp=0xc0001372e8 pc=0x10443d9
github.com/tidwall/rtree/base.(*treeItem).unsafeNode(...)
	/Users/olone/go/pkg/mod/github.com/tidwall/rtree@v0.0.0-20180113144539-6cd427091e0e/base/rtree.go:187
github.com/tidwall/rtree/base.(*RTree).insert(0xc00024c000, 0xc00007c6c0, 0x1296c60, 0xc0002483c0, 0x0, 0xc000058c00)
	/Users/olone/go/pkg/mod/github.com/tidwall/rtree@v0.0.0-20180113144539-6cd427091e0e/base/rtree.go:242 +0x2bc fp=0xc000137408 sp=0xc000137318 pc=0x12179cc
github.com/tidwall/rtree/base.(*RTree).Insert(0xc00024c000, 0xc000234990, 0x2, 0x2, 0xc0002349a0, 0x2, 0x2, 0x1296c60, 0xc0002483c0)
	/Users/olone/go/pkg/mod/github.com/tidwall/rtree@v0.0.0-20180113144539-6cd427091e0e/base/rtree.go:227 +0x1cd fp=0xc0001374b8 sp=0xc000137408 pc=0x121765d
github.com/tidwall/rtree.(*RTree).Insert(0xc0001691c0, 0x12fef00, 0xc0002483c0)
	/Users/olone/go/pkg/mod/github.com/tidwall/rtree@v0.0.0-20180113144539-6cd427091e0e/rtree.go:57 +0x2f7 fp=0xc000137598 sp=0xc0001374b8 pc=0x121b9a7
github.com/tidwall/buntdb.(*DB).insertIntoDatabase(0xc00012a160, 0xc0002483c0, 0xc0001376f8)
	/Users/olone/playground/buntdb/buntdb.go:494 +0x456 fp=0xc0001376a8 sp=0xc000137598 pc=0x12236a6
github.com/tidwall/buntdb.(*Tx).Set(0xc00000e700, 0x12bb6d9, 0x6, 0x12bd469, 0xf, 0x0, 0x1008710, 0xc000137868, 0x104a0bc, 0x1007970, ...)
	/Users/olone/playground/buntdb/buntdb.go:1378 +0x1cc fp=0xc000137780 sp=0xc0001376a8 pc=0x122b89c
github.com/tidwall/buntdb.TestVariousTx.func13(0xc00000e700, 0xc000137801, 0xc00000e700)
	/Users/olone/playground/buntdb/buntdb_test.go:950 +0x515 fp=0xc000137940 sp=0xc000137780 pc=0x1254245
github.com/tidwall/buntdb.(*DB).managed(0xc00012a160, 0x12bb101, 0xc000137e40, 0x0, 0x0)
	/Users/olone/playground/buntdb/buntdb.go:949 +0x153 fp=0xc000137a30 sp=0xc000137940 pc=0x1226f33
github.com/tidwall/buntdb.(*DB).Update(...)
	/Users/olone/playground/buntdb/buntdb.go:972
github.com/tidwall/buntdb.TestVariousTx(0xc00017e240)
	/Users/olone/playground/buntdb/buntdb_test.go:928 +0x171f fp=0xc000137ed0 sp=0xc000137a30 pc=0x123778f
testing.tRunner(0xc00017e240, 0x12c7870)
	/usr/local/go/src/testing/testing.go:991 +0x1ec fp=0xc000137fd0 sp=0xc000137ed0 pc=0x11721bc
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc000137fd8 sp=0xc000137fd0 pc=0x10a4851
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1042 +0x661

goroutine 1 [chan receive]:
testing.(*T).Run(0xc000158000, 0x12bce1d, 0xd, 0x12c7870, 0x1)
	/usr/local/go/src/testing/testing.go:1043 +0x699
testing.runTests.func1(0xc000158000)
	/usr/local/go/src/testing/testing.go:1284 +0xa7
testing.tRunner(0xc000158000, 0xc000135d50)
	/usr/local/go/src/testing/testing.go:991 +0x1ec
testing.runTests(0xc000138020, 0x14697a0, 0x20, 0x20, 0x0)
	/usr/local/go/src/testing/testing.go:1282 +0x528
testing.(*M).Run(0xc00014e080, 0x0)
	/usr/local/go/src/testing/testing.go:1199 +0x300
main.main()
	_testmain.go:168 +0x224

goroutine 40 [chan receive]:
github.com/tidwall/buntdb.(*DB).backgroundManager(0xc000142210)
	/Users/olone/playground/buntdb/buntdb.go:536 +0x2c7
created by github.com/tidwall/buntdb.Open
	/Users/olone/playground/buntdb/buntdb.go:171 +0x640

goroutine 14 [chan receive]:
github.com/tidwall/buntdb.(*DB).backgroundManager(0xc0001422c0)
	/Users/olone/playground/buntdb/buntdb.go:536 +0x2c7
created by github.com/tidwall/buntdb.Open
	/Users/olone/playground/buntdb/buntdb.go:171 +0x640

goroutine 16 [chan receive]:
github.com/tidwall/buntdb.(*DB).backgroundManager(0xc000142370)
	/Users/olone/playground/buntdb/buntdb.go:536 +0x2c7
created by github.com/tidwall/buntdb.Open
	/Users/olone/playground/buntdb/buntdb.go:171 +0x640

goroutine 50 [chan receive]:
github.com/tidwall/buntdb.(*DB).backgroundManager(0xc000142420)
	/Users/olone/playground/buntdb/buntdb.go:536 +0x2c7
created by github.com/tidwall/buntdb.Open
	/Users/olone/playground/buntdb/buntdb.go:171 +0x640

goroutine 52 [chan receive]:
github.com/tidwall/buntdb.(*DB).backgroundManager(0xc0001424d0)
	/Users/olone/playground/buntdb/buntdb.go:536 +0x2c7
created by github.com/tidwall/buntdb.Open
	/Users/olone/playground/buntdb/buntdb.go:171 +0x640

goroutine 54 [chan receive]:
github.com/tidwall/buntdb.(*DB).backgroundManager(0xc000142580)
	/Users/olone/playground/buntdb/buntdb.go:536 +0x2c7
created by github.com/tidwall/buntdb.Open
	/Users/olone/playground/buntdb/buntdb.go:171 +0x640

goroutine 42 [chan receive]:
github.com/tidwall/buntdb.(*DB).backgroundManager(0xc0004c4000)
	/Users/olone/playground/buntdb/buntdb.go:536 +0x2c7
created by github.com/tidwall/buntdb.Open
	/Users/olone/playground/buntdb/buntdb.go:171 +0x640

goroutine 43 [chan receive]:
github.com/tidwall/buntdb.(*DB).backgroundManager(0xc0004c40b0)
	/Users/olone/playground/buntdb/buntdb.go:536 +0x2c7
created by github.com/tidwall/buntdb.Open
	/Users/olone/playground/buntdb/buntdb.go:171 +0x640

goroutine 24 [chan receive]:
github.com/tidwall/buntdb.(*DB).backgroundManager(0xc00012a000)
	/Users/olone/playground/buntdb/buntdb.go:536 +0x2c7
created by github.com/tidwall/buntdb.Open
	/Users/olone/playground/buntdb/buntdb.go:171 +0x640

goroutine 26 [chan receive]:
github.com/tidwall/buntdb.(*DB).backgroundManager(0xc00012a0b0)
	/Users/olone/playground/buntdb/buntdb.go:536 +0x2c7
created by github.com/tidwall/buntdb.Open
	/Users/olone/playground/buntdb/buntdb.go:171 +0x640

goroutine 28 [chan receive]:
github.com/tidwall/buntdb.(*DB).backgroundManager(0xc00012a160)
	/Users/olone/playground/buntdb/buntdb.go:536 +0x2c7
created by github.com/tidwall/buntdb.Open
	/Users/olone/playground/buntdb/buntdb.go:171 +0x640
FAIL	github.com/tidwall/buntdb	5.555s
FAIL
```

**Comment by tidwall** [comment]
This issue has been resolved. Thanks for reporting.
